### PR TITLE
add mail processing for "multipart/alternative" and add interrupt idle runnable

### PR DESCRIPTION
**Pull request by FlowsenAusMonotown**

### CODE REVIEW

**Comment by saig0** [comment]
@FlowsenAusMonotown thank you for your contribution :tada: 

Your PR changed the formatting of the files. With the formatting, it is very hard to see your changes. Please undo the formatting and commit only your code changes. 

I see also no test in the PR. Please think about adding a test case to verify the behavior.

**Review by saig0 — COMMENTED** [review]
@FlowsenAusMonotown thank you for your contribution :tada: 

Your PR changed the formatting of the files. With the formatting, it is very hard to see your changes. Please undo the formatting and commit only your code changes. 

I see also no test in the PR. Please think about adding a test case to verify the behavior.

**Comment by FlowsenAusMonotown** [comment]
@saig0 Is there a code formatter, which I can use? This would be very helpful. I will have a look, if there are any possibilities to test the new behaviour.

**Comment by saig0** [comment]
@FlowsenAusMonotown regarding the formatting, please have a look at https://github.com/camunda-community-hub/camunda-platform-7-mail/pull/54#issuecomment-1201047213.

**Comment by jonathanlukas** [comment]
Hi @FlowsenAusMonotown , I just bumped the repo a bit forward. Could you please also forward your repo.

To properly format your code, you can now run `mvn clean install` which will apply a formatter.

**Pull request closed without merging**
